---
fixtures:
  repositories:
    augeasproviders_core:
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub:
      repo: "https://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    compliance_markup: "https://github.com/simp/pupmod-simp-compliance_markup"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
  symlinks:
    tpm: "#{source_dir}"
