---
fixtures:
  repositories:
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    concat: https://github.com/simp/puppetlabs-concat
    ima: https://github.com/simp/pupmod-simp-ima
    rsync: https://github.com/simp/pupmod-simp-rsync
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    yum: https://github.com/simp/puppet-yum
  symlinks:
    tpm: "#{source_dir}"
