<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - server
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
  el6:
    roles:
      - server
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: disabled
  ssh:
    timeout: 2
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
# vb_gui: true
